AWSTemplateFormatVersion: "2010-09-09"
Description: "Arquitectura Acoplada en ECS Fargate + DynamoDB + NLB interno + API Gateway con API Key (LabRole automatico, CORS habilitado y rutas /items + /items/{id})"

Parameters:
  EcrRepositoryName:
    Type: String
    Default: inventory-app
    Description: Nombre del repositorio ECR ya existente

  DynamoTableName:
    Type: String
    Default: products
    Description: Nombre de la tabla DynamoDB ya existente

  ImageTag:
    Type: String
    Default: latest
    Description: Tag de la imagen Docker a usar en ECS

Resources:
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG para ECS Fargate
      VpcId: vpc-08e3017d59efd8684
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: inventory-sg

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: inventory-cluster

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/inventory-app
      RetentionInDays: 7

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: inventory-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      TaskRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      ContainerDefinitions:
        - Name: inventory-container
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EcrRepositoryName}:${ImageTag}"
          PortMappings:
            - ContainerPort: 8080
          Environment:
            - Name: DYNAMO_TABLE
              Value: !Ref DynamoTableName
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs

  NetworkLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: inventory-nlb
      Type: network
      Scheme: internal
      Subnets:
        - subnet-075de69e3bb890936
        - subnet-07567421b26427197

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: inventory-tg
      Port: 8080
      Protocol: TCP
      TargetType: ip
      VpcId: vpc-08e3017d59efd8684
      HealthCheckProtocol: TCP
      HealthCheckPort: "traffic-port"
      HealthCheckIntervalSeconds: 30
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref NetworkLoadBalancer
      Port: 8080
      Protocol: TCP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  ECSService:
    Type: AWS::ECS::Service
    DependsOn: Listener
    Properties:
      Cluster: !Ref ECSCluster
      ServiceName: inventory-service
      LaunchType: FARGATE
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - subnet-075de69e3bb890936
            - subnet-07567421b26427197
          SecurityGroups:
            - !Ref ECSSecurityGroup
      LoadBalancers:
        - TargetGroupArn: !Ref TargetGroup
          ContainerName: inventory-container
          ContainerPort: 8080
      HealthCheckGracePeriodSeconds: 30

  ApiGatewayVpcLink:
    Type: AWS::ApiGateway::VpcLink
    Properties:
      Name: inventory-vpc-link
      TargetArns:
        - !Ref NetworkLoadBalancer

  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: inventory-api
      Description: API Gateway para el servicio Inventory
      EndpointConfiguration:
        Types: [REGIONAL]

  ApiGatewayResourceItems:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: items
      RestApiId: !Ref ApiGatewayRestApi

  ApiGatewayResourceItemById:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref ApiGatewayResourceItems
      PathPart: "{id}"
      RestApiId: !Ref ApiGatewayRestApi

  # ===================================
  # MÉTODOS HTTP (CORS + API KEY)
  # ===================================
  PostItemsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceItems
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "http://${NetworkLoadBalancer.DNSName}:8080/items"
        ConnectionType: VPC_LINK
        ConnectionId: !Ref ApiGatewayVpcLink

  GetItemsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceItems
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: GET
        Uri: !Sub "http://${NetworkLoadBalancer.DNSName}:8080/items"
        ConnectionType: VPC_LINK
        ConnectionId: !Ref ApiGatewayVpcLink

  GetItemMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceItemById
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      RequestParameters:
        method.request.path.id: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: GET
        Uri: !Sub "http://${NetworkLoadBalancer.DNSName}:8080/items/{id}"
        ConnectionType: VPC_LINK
        ConnectionId: !Ref ApiGatewayVpcLink
        RequestParameters:
          integration.request.path.id: method.request.path.id

  PutItemMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceItemById
      HttpMethod: PUT
      AuthorizationType: NONE
      ApiKeyRequired: true
      RequestParameters:
        method.request.path.id: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: PUT
        Uri: !Sub "http://${NetworkLoadBalancer.DNSName}:8080/items/{id}"
        ConnectionType: VPC_LINK
        ConnectionId: !Ref ApiGatewayVpcLink
        RequestParameters:
          integration.request.path.id: method.request.path.id

  DeleteItemMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceItemById
      HttpMethod: DELETE
      AuthorizationType: NONE
      ApiKeyRequired: true
      RequestParameters:
        method.request.path.id: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: DELETE
        Uri: !Sub "http://${NetworkLoadBalancer.DNSName}:8080/items/{id}"
        ConnectionType: VPC_LINK
        ConnectionId: !Ref ApiGatewayVpcLink
        RequestParameters:
          integration.request.path.id: method.request.path.id

  # ===================================
  # MÉTODOS OPTIONS (CORS)
  # ===================================
  OptionsItemsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceItems
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,x-api-key'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  OptionsItemMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceItemById
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,x-api-key'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - PostItemsMethod
      - GetItemsMethod
      - GetItemMethod
      - PutItemMethod
      - DeleteItemMethod
      - OptionsItemsMethod
      - OptionsItemMethod
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      StageName: prod

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: inventory-api-key
      Enabled: true

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: ApiGatewayDeployment
    Properties:
      UsagePlanName: inventory-usage-plan
      ApiStages:
        - ApiId: !Ref ApiGatewayRestApi
          Stage: prod

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

Outputs:
  ClusterName:
    Description: Nombre del Cluster ECS
    Value: !Ref ECSCluster

  LoadBalancerDNS:
    Description: DNS del NLB
    Value: !GetAtt NetworkLoadBalancer.DNSName

  ApiEndpoint:
    Description: Endpoint del API Gateway
    Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/items"

  ApiKeyValue:
    Description: API Key para llamadas
    Value: !Ref ApiKey
